### ISSUE TITLE
suggestion: jsoid

### ISSUE THREAD

**Issue by loveencounterflow** [Medium/oid#4]
hi, i'm the author of [jsoid](https://github.com/loveencounterflow/jsoid), a JavaScript-only implementation of object IDs which runs everywhere where `WeakMap`s are available (i.e. NodeJS > 0.11.x, 0.12, io.js, [6to5](http://6to5.org/), and [some browsers](http://kangax.github.io/compat-table/es6/#WeakMap)). There is a `WeakMap` implementation in 6to5, so it should be possible to write OIDs in ES5 using a shim. Just sayin.

**Comment by nicks** [comment]
ok. free software is like free speech and free beer: the more, the better. is there anything that you need?

**Comment by loveencounterflow** [comment]
not criticizing here or anything; i just thought that instead of writing C and maintaining a map implementation of your own (?) you might just as well look into `WeakMap`s and use those where available. There's also [a few `WeakMap` shims](https://github.com/Benvie/WeakMap) around. 

A question for you: when using, say, `oid.hash( d )`, do i have to remember to clear object `d` when it goes out of scope—that is, is there a reference to `d` kept by `oid`?

**Comment by danfuzz** [comment]
[Note: I'm the original author of oid, though I haven't touched the code in a couple years.]

> when using, say, oid.hash( d ), do i have to remember to clear object d when it goes out of scope—that is, is there a reference to d kept by oid?

Nope. This code uses V8's native-accessible object identity mechanism. Oid itself doesn't have to augment objects with anything, nor does it have to keep its own list / set / whatever of "identified" objects.

Based on a quick read of jsoid, it looks to me like it's a lot heavier-weight than oid, and that the mechanism is semantically leaky. That is, you can reflect on an object and see whether it's part of a WeakMap, and you can probably mess with a WeakMap if you happen to hold a reference to an object held in that map. I'm guessing that jsoid will also fail when trying to add immutable objects as keys. For jsoid's clients, of course, this state of affairs may be just fine; I just wanted to point out that oid makes a different set of tradeoffs.

**Comment by danfuzz** [comment]
PS: Feel free to update the "Author" info.

**Comment by danfuzz** [comment]
I wrote:
> Based on a quick read of jsoid

Mis-spoke. What I meant was, based on a quick read of the WeakMap shim, and on the assumption that jsoid uses that or something like it, the characteristics I indicated would be the case.

**Comment by loveencounterflow** [comment]
@danfuzz yeah i made that discovery too when inspecting that particular shim. I'm not even surprised the shim is not 100% side-effect free; of course, accessing the VM's own identity mechanism is much cooler, more correct, and has been missing in JavaScript for 20 years. And yeah, that the shim will probably fail with frozen objects limits its usability and opens the door for nasty (silent?) failures.

BTW i'm getting a deprecation warning `child_process: customFds option is deprecated, use stdio instead.` when compiling `oid`; is that expected behavior?

**Comment by danfuzz** [comment]
> BTW i'm getting a deprecation warning child_process: customFds option is deprecated, use stdio 
> instead. when compiling oid; is that expected behavior?

(Not clear if this was directed at me…) When last I used oid, a couple years ago, it compiled and ran without warnings. Can't really tell you more than that, sorry.

**Comment by nicks** [comment]
ok! I just did the minimum amount to get this to work on node 0.12, so I could move on to help get the rest of the world updated. I'll eventually come back around to update the maintainer and deprecation warning.
